/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface CreateLobbyRequest
 */
export interface CreateLobbyRequest {
    /**
     * 
     * @type {User}
     * @memberof CreateLobbyRequest
     */
    user?: User;
}

/**
 * Check if a given object implements the CreateLobbyRequest interface.
 */
export function instanceOfCreateLobbyRequest(value: object): value is CreateLobbyRequest {
    return true;
}

export function CreateLobbyRequestFromJSON(json: any): CreateLobbyRequest {
    return CreateLobbyRequestFromJSONTyped(json, false);
}

export function CreateLobbyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLobbyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
    };
}

export function CreateLobbyRequestToJSON(json: any): CreateLobbyRequest {
    return CreateLobbyRequestToJSONTyped(json, false);
}

export function CreateLobbyRequestToJSONTyped(value?: CreateLobbyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserToJSON(value['user']),
    };
}

