/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Dimension
 */
export interface Dimension {
    /**
     * 
     * @type {string}
     * @memberof Dimension
     */
    left?: string;
    /**
     * 
     * @type {string}
     * @memberof Dimension
     */
    right?: string;
}

/**
 * Check if a given object implements the Dimension interface.
 */
export function instanceOfDimension(value: object): value is Dimension {
    return true;
}

export function DimensionFromJSON(json: any): Dimension {
    return DimensionFromJSONTyped(json, false);
}

export function DimensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dimension {
    if (json == null) {
        return json;
    }
    return {
        
        'left': json['left'] == null ? undefined : json['left'],
        'right': json['right'] == null ? undefined : json['right'],
    };
}

export function DimensionToJSON(json: any): Dimension {
    return DimensionToJSONTyped(json, false);
}

export function DimensionToJSONTyped(value?: Dimension | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'left': value['left'],
        'right': value['right'],
    };
}

