/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface JoinLobbyResponse
 */
export interface JoinLobbyResponse {
    /**
     * 
     * @type {string}
     * @memberof JoinLobbyResponse
     */
    lobbyId?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof JoinLobbyResponse
     */
    users?: Array<User>;
}

/**
 * Check if a given object implements the JoinLobbyResponse interface.
 */
export function instanceOfJoinLobbyResponse(value: object): value is JoinLobbyResponse {
    return true;
}

export function JoinLobbyResponseFromJSON(json: any): JoinLobbyResponse {
    return JoinLobbyResponseFromJSONTyped(json, false);
}

export function JoinLobbyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinLobbyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'lobbyId': json['lobbyId'] == null ? undefined : json['lobbyId'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserFromJSON)),
    };
}

export function JoinLobbyResponseToJSON(json: any): JoinLobbyResponse {
    return JoinLobbyResponseToJSONTyped(json, false);
}

export function JoinLobbyResponseToJSONTyped(value?: JoinLobbyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lobbyId': value['lobbyId'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserToJSON)),
    };
}

