/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinLobbyRequest
 */
export interface JoinLobbyRequest {
    /**
     * 
     * @type {string}
     * @memberof JoinLobbyRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoinLobbyRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the JoinLobbyRequest interface.
 */
export function instanceOfJoinLobbyRequest(value: object): value is JoinLobbyRequest {
    return true;
}

export function JoinLobbyRequestFromJSON(json: any): JoinLobbyRequest {
    return JoinLobbyRequestFromJSONTyped(json, false);
}

export function JoinLobbyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinLobbyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function JoinLobbyRequestToJSON(json: any): JoinLobbyRequest {
    return JoinLobbyRequestToJSONTyped(json, false);
}

export function JoinLobbyRequestToJSONTyped(value?: JoinLobbyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

