/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
    PointToJSONTyped,
} from './Point';

/**
 * 
 * @export
 * @interface PointGuessRequest
 */
export interface PointGuessRequest {
    /**
     * 
     * @type {Point}
     * @memberof PointGuessRequest
     */
    guess?: Point;
}

/**
 * Check if a given object implements the PointGuessRequest interface.
 */
export function instanceOfPointGuessRequest(value: object): value is PointGuessRequest {
    return true;
}

export function PointGuessRequestFromJSON(json: any): PointGuessRequest {
    return PointGuessRequestFromJSONTyped(json, false);
}

export function PointGuessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointGuessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guess': json['guess'] == null ? undefined : PointFromJSON(json['guess']),
    };
}

export function PointGuessRequestToJSON(json: any): PointGuessRequest {
    return PointGuessRequestToJSONTyped(json, false);
}

export function PointGuessRequestToJSONTyped(value?: PointGuessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guess': PointToJSON(value['guess']),
    };
}

