/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
    PointToJSONTyped,
} from './Point';

/**
 * 
 * @export
 * @interface Score
 */
export interface Score {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof Score
     */
    previousScores?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof Score
     */
    gainedScores?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof Score
     */
    newScores?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: Point; }}
     * @memberof Score
     */
    userGuesses?: { [key: string]: Point; };
}

/**
 * Check if a given object implements the Score interface.
 */
export function instanceOfScore(value: object): value is Score {
    return true;
}

export function ScoreFromJSON(json: any): Score {
    return ScoreFromJSONTyped(json, false);
}

export function ScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Score {
    if (json == null) {
        return json;
    }
    return {
        
        'previousScores': json['previousScores'] == null ? undefined : json['previousScores'],
        'gainedScores': json['gainedScores'] == null ? undefined : json['gainedScores'],
        'newScores': json['newScores'] == null ? undefined : json['newScores'],
        'userGuesses': json['userGuesses'] == null ? undefined : (mapValues(json['userGuesses'], PointFromJSON)),
    };
}

export function ScoreToJSON(json: any): Score {
    return ScoreToJSONTyped(json, false);
}

export function ScoreToJSONTyped(value?: Score | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'previousScores': value['previousScores'],
        'gainedScores': value['gainedScores'],
        'newScores': value['newScores'],
        'userGuesses': value['userGuesses'] == null ? undefined : (mapValues(value['userGuesses'], PointToJSON)),
    };
}

