/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Score } from './Score';
import {
    ScoreFromJSON,
    ScoreFromJSONTyped,
    ScoreToJSON,
    ScoreToJSONTyped,
} from './Score';

/**
 * 
 * @export
 * @interface ScoreResponse
 */
export interface ScoreResponse {
    /**
     * 
     * @type {Score}
     * @memberof ScoreResponse
     */
    score?: Score;
}

/**
 * Check if a given object implements the ScoreResponse interface.
 */
export function instanceOfScoreResponse(value: object): value is ScoreResponse {
    return true;
}

export function ScoreResponseFromJSON(json: any): ScoreResponse {
    return ScoreResponseFromJSONTyped(json, false);
}

export function ScoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : ScoreFromJSON(json['score']),
    };
}

export function ScoreResponseToJSON(json: any): ScoreResponse {
    return ScoreResponseToJSONTyped(json, false);
}

export function ScoreResponseToJSONTyped(value?: ScoreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': ScoreToJSON(value['score']),
    };
}

