/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordGuess
 */
export interface WordGuess {
    /**
     * 
     * @type {string}
     * @memberof WordGuess
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WordGuess
     */
    word?: string;
}

/**
 * Check if a given object implements the WordGuess interface.
 */
export function instanceOfWordGuess(value: object): value is WordGuess {
    return true;
}

export function WordGuessFromJSON(json: any): WordGuess {
    return WordGuessFromJSONTyped(json, false);
}

export function WordGuessFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordGuess {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'word': json['word'] == null ? undefined : json['word'],
    };
}

export function WordGuessToJSON(json: any): WordGuess {
    return WordGuessToJSONTyped(json, false);
}

export function WordGuessToJSONTyped(value?: WordGuess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'word': value['word'],
    };
}

