/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordGuessResponse
 */
export interface WordGuessResponse {
    /**
     * 
     * @type {boolean}
     * @memberof WordGuessResponse
     */
    showWaitingScreen?: boolean;
}

/**
 * Check if a given object implements the WordGuessResponse interface.
 */
export function instanceOfWordGuessResponse(value: object): value is WordGuessResponse {
    return true;
}

export function WordGuessResponseFromJSON(json: any): WordGuessResponse {
    return WordGuessResponseFromJSONTyped(json, false);
}

export function WordGuessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordGuessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'showWaitingScreen': json['showWaitingScreen'] == null ? undefined : json['showWaitingScreen'],
    };
}

export function WordGuessResponseToJSON(json: any): WordGuessResponse {
    return WordGuessResponseToJSONTyped(json, false);
}

export function WordGuessResponseToJSONTyped(value?: WordGuessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showWaitingScreen': value['showWaitingScreen'],
    };
}

