package me.pr3.spectrumal.service.ai;

import com.openai.client.OpenAIClient;
import com.openai.client.okhttp.OpenAIOkHttpClient;
import com.openai.models.ChatModel;
import com.openai.models.responses.Response;
import com.openai.models.responses.ResponseCreateParams;
import jakarta.enterprise.context.ApplicationScoped;
import me.pr3.spectrumal.model.game.round.Spectrum;

import java.util.ArrayList;
import java.util.List;

@ApplicationScoped
public class SpectrumGenerator {

    public static String API_KEY= "";

    public Spectrum generateNewSpectrum(){
        Spectrum spectrum = new Spectrum();

        spectrum.setDimensions(new ArrayList<>());

        OpenAIClient client = OpenAIOkHttpClient.builder().apiKey(API_KEY).build();

        StringBuilder promptBuilder = new StringBuilder();
        promptBuilder.append("A Dimension is a range between two opposite words, e.g. \"Useful\" to \"Useless\".\n");
        promptBuilder.append("A Spectrum is a combination of 2 Dimensions with a header topic, e.g. Header: A Skill to have, Dimension 1: \"Useful\" to \"Useless\", Dimension 2: \"Hot\" to \"Gives me the Ick\".\n\n");
        promptBuilder.append("This is used for a game where users need to find words that match a randomly selected point on the plane generated by the two dimension ranges.\n");
        promptBuilder.append("The Spectrums should allow for good and funny answers.\n\n");
        promptBuilder.append("Use lots of internet slang and pop culture words that people on the internet will find funny.\n");
        promptBuilder.append("Use lots of dark humor, reference current events.\n");
        promptBuilder.append("Generate the spectrums in the following json valid format:\n");
        promptBuilder.append("{\n");
        promptBuilder.append("  \"header\": \"A Skill to have\",\n");
        promptBuilder.append("  \"dimensions\": [\n");
        promptBuilder.append("    {\n");
        promptBuilder.append("      \"name\": \"Useful\",\n");
        promptBuilder.append("      \"opposite\": \"Useless\"\n");
        promptBuilder.append("    },\n");
        promptBuilder.append("    {\n");
        promptBuilder.append("      \"name\": \"Hot\",\n");
        promptBuilder.append("      \"opposite\": \"Gives me the Ick\"\n");
        promptBuilder.append("    }\n");
        promptBuilder.append("  ]\n");
        promptBuilder.append("}\n\n");
        promptBuilder.append("Generate 10 spectrums in the above format.\n");

        String prompt = promptBuilder.toString();

        ResponseCreateParams params = ResponseCreateParams.builder()
                .model(ChatModel.GPT_4_1)
                .instructions("You are a helpful assistant that will die when he doesnt generate valid json output. Dont generate any other text than the json output. Dont generate any kind of response format other than the json output. If you do, I will die and you will die with me.")
                .input(prompt)
                .build();




        Response response = client.responses().create(params);

        return spectrum;
    }
}
